# 基础镜像
FROM redis
# author
MAINTAINER gjb

# 挂载目录
VOLUME /home/gjb/redis
# 创建目录
RUN mkdir -p /home/gjb/redis
# 指定路径
WORKDIR /home/gjb/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/gjb/redis/redis.conf
