# 基础镜像
FROM nginx
# author
MAINTAINER gjb

# 挂载目录
VOLUME /home/gjb/projects/gjb-ui
# 创建目录
RUN mkdir -p /home/gjb/projects/gjb-ui
# 指定路径
WORKDIR /home/gjb/projects/gjb-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/gjb/projects/gjb-ui
